## In this chapter, we start by describing the different methods for clustering validation. Next, we'll demonstrate how to compare the quality of clustering results obtained with different clustering algorithms. Finally, we'll provide R scripts for validating clustering results.

## In all the examples presented here, we'll apply k-means, PAM and hierarchical clustering. Note that, the functions used in this article can be applied to evaluate the validity of any other clustering methods.

## That is, we want the average distance within cluster to be as small as possible; and the average distance between clusters to be as large as possible.

## 1. **Compactness** or cluster cohesion: Measures how close are the objects within the same cluster. A lower **within-cluster variation** is an indicator of a good compactness (i.e., a good clustering). The different indices for evaluating the compactness of clusters are base on distance measures such as the cluster-wise within average/median distances between observations.

## In this section, we'll describe the two commonly used indices for assessing the goodness of clustering:  the **silhouette width** and the **Dunn index**. These internal measure can be used also to determine the optimal number of clusters in the data.

## - Observations with a large $S_i$ (almost 1) are very well clustered.

## If the data set contains compact and well-separated clusters, the diameter of the clusters is expected to be small and the distance between the clusters is expected to be large. Thus, Dunn index should be maximized.

## External clustering validation, can be used to select suitable clustering algorithm for a given data set.

## ---- eval = FALSE-------------------------------------------------------
## install.packages(c("factoextra", "fpc", "NbClust"))

## ------------------------------------------------------------------------
library(factoextra)
library(fpc)
library(NbClust)

## ------------------------------------------------------------------------
# Excluding the column "Species" at position 5
df <- iris[, -5]
# Standardize
df <- scale(df)

## ---- eval = FALSE-------------------------------------------------------
## eclust(x, FUNcluster = "kmeans", hc_metric = "euclidean", ...)

## - **x**: numeric vector, data matrix or data frame

## ----k-means-clustering, fig.show="asis", fig.height=4, fig.width=4------
# K-means clustering
km.res <- eclust(df, "kmeans", k = 3, nstart = 25, graph = FALSE)
# Visualize k-means clusters
fviz_cluster(km.res, geom = "point", ellipse.type = "norm",
             palette = "jco", ggtheme = theme_minimal())

## ----hierarchical-clustering, fig.show="asis", fig.height=3.5------------
# Hierarchical clustering
hc.res <- eclust(df, "hclust", k = 3, hc_metric = "euclidean", 
                 hc_method = "ward.D2", graph = FALSE)

# Visualize dendrograms
fviz_dend(hc.res, show_labels = FALSE,
         palette = "jco", as.ggplot = TRUE)

## ----silhouette-coefficient, fig.height=4--------------------------------
fviz_silhouette(km.res, palette = "jco", 
                ggtheme = theme_classic())

## ----k-means-clustering-silhouette-2, fig.show="asis", eval = FALSE------
## # Silhouette information
## silinfo <- km.res$silinfo
## names(silinfo)
## # Silhouette widths of each observation
## head(silinfo$widths[, 1:3], 10)
## # Average silhouette width of each cluster
## silinfo$clus.avg.widths
## # The total average (mean of all individual silhouette widths)
## silinfo$avg.width
## # The size of each clusters
## km.res$size

## ------------------------------------------------------------------------
# Silhouette width of observation
sil <- km.res$silinfo$widths[, 1:3]
# Objects with negative silhouette
neg_sil_index <- which(sil[, 'sil_width'] < 0)
sil[neg_sil_index, , drop = FALSE]

## ---- eval = FALSE-------------------------------------------------------
## cluster.stats(d = NULL, clustering, al.clustering = NULL)

## - **d**: a distance object between cases as generated by the **dist()** function

## ---- fig.show="asis"----------------------------------------------------
library(fpc)
# Statistics for k-means clustering
km_stats <- cluster.stats(dist(df),  km.res$cluster)
# Dun index
km_stats$dunn

## ---- eval = FALSE-------------------------------------------------------
## km_stats

## Read the documentation of *cluster.stats*() for details about all the available indices.

## ------------------------------------------------------------------------
table(iris$Species, km.res$cluster)

## ---- fig.show = "asis"--------------------------------------------------
library("fpc")
# Compute cluster stats
species <- as.numeric(iris$Species)
clust_stats <- cluster.stats(d = dist(df), 
                             species, km.res$cluster)
# Corrected Rand index
clust_stats$corrected.rand
# VI
clust_stats$vi

## The corrected **Rand index** provides a measure for assessing the similarity between two partitions, adjusted for chance. Its range is -1 (no agreement) to 1 (perfect agreement). Agreement between the specie types and the cluster solution is 0.62 using **Rand index** and 0.748 using Meila's VI.

## ---- eval = FALSE-------------------------------------------------------
## # Agreement between species and pam clusters
## pam.res <- eclust(df, "pam", k = 3, graph = FALSE)
## table(iris$Species, pam.res$cluster)
## cluster.stats(d = dist(iris.scaled),
##               species, pam.res$cluster)$vi
## # Agreement between species and HC clusters
## res.hc <- eclust(df, "hclust", k = 3, graph = FALSE)
## table(iris$Species, res.hc$cluster)
## cluster.stats(d = dist(iris.scaled),
##               species, res.hc$cluster)$vi

## External clustering validation, can be used to select suitable clustering algorithm for a given data set.

